version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8008:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/code
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./:/code
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-laravel
      MYSQL_USER: irin
      MYSQL_PASSWORD: 2004
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
volumes:
  mysql: